### ISSUE TITLE
in some project jsprettier won't work. 

### ISSUE THREAD

**Issue by berkaey** [jonlabelle/SublimeJsPrettier#104]
hey there, jsprettier works on some projects but not on others and gives me this. 

```Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "/Users/berkaey/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 204, in run
    prettier_config_path = resolve_prettier_config(view)
  File "/Users/berkaey/Library/Application Support/Sublime Text 3/Packages/JsPrettier/jsprettier/sthelper.py", line 206, in resolve_prettier_config
    resolved_prettier_config_path = find_prettier_config(get_file_abs_dir(source_file))
  File "/Users/berkaey/Library/Application Support/Sublime Text 3/Packages/JsPrettier/jsprettier/util.py", line 47, in find_prettier_config
    if os.path.basename(prettier_config) == 'package.json' and _prettier_opts_in_package_json(prettier_config):
  File "/Users/berkaey/Library/Application Support/Sublime Text 3/Packages/JsPrettier/jsprettier/util.py", line 113, in _prettier_opts_in_package_json
    json_data = json.load(package_file, encoding='utf-8')
  File "./python3.3/json/__init__.py", line 268, in load
  File "./python3.3/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1469: ordinal not in range(128)```

**Comment by jonlabelle** [comment]
It's likely the package.json file being discovered has a BOM mark in it, or isn't encoded with utf-8. I'll put in a temp fix for now to ignore the exception... but just note that prettier will also throw an error if your package.json isn't encoded w/ utf8.
