### ISSUE TITLE
Prettier plugin fails to load after OS update.

### ISSUE THREAD

**Issue by iamcam** [jonlabelle/SublimeJsPrettier#106]
### Explain the Issue and Expected Behavior

I noticed that prettier was no longer auto-formatting my JS files in Sublime Text 3

### Prettier version

To show the currently installed prettier version, run the following command:

    $ prettier --version
   1.9.2

### JsPrettier Plug-in Version

The JsPrettier Sublime Text Plug-in version is located in the `package.json` file.

1.20.8

### Platform Details

Provide your Sublime Text version and Platform details.

**Example**

    - Sublime Text Version: 3.0
    - Sublime Text Build: 3143
    - Operating System Name: MacOS X
    - Operating System Version: High Sierra - 10.13.3

### Generated Prettier command line arguments

Nothing is generated
### Is the same behavior observed when run against Prettier directly?

No - Prettier is not loading/cannot run. Console shows

```
reloading plugin JsPrettier.JsPrettier
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/foouser/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 76, in <module>
    from .jsprettier.util import \
ImportError: cannot import name in_source_file_path_or_project_root
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

### The contents of your `User/JsPrettier.sublime-settings` file

```
{
  "prettier_cli_path": "",
  "debug": true,
  "auto_format_on_save": true,
  "prettier_options": {
    "singleQuote": true,
    "trailingComma": "es5"
  },
  "auto_format_on_save_excludes": [
    "*.md"
  ]
}
```    

### The contents of your `<project_name>.sublime-project` file (if applicable)

N/A

### Steps to reproduce the behavior

1. Launch Sublime
2. Make an edit to a JS file - something intentional that should be updated by prettier
3. Observe Prettier is not running.
4. Observe right-clicking in the text file shows the "JSPrettier Format Code" option is grayed out
5. Open the Sublime console
6. Observe the following output (this was after trying to remove and re-install the package):

```
reloading plugin JsPrettier.JsPrettier
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/foouser/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 76, in <module>
    from .jsprettier.util import \
ImportError: cannot import name in_source_file_path_or_project_root
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

Prettier Plugin fails to run altogether.

**Comment by jonlabelle** [comment]
Try closing, re-opening Sublime Text 3.
