### ISSUE TITLE
`js_prettier` command not running

### ISSUE THREAD

**Issue by MaxGuitet** [jonlabelle/SublimeJsPrettier#108]
When running the `js_prettier` command, nothing happens both on keybinding and direct command line, and no error is raised. Rolling back to 1.20.8 fixes the issue.

I'm using an external .prettierrc.json file but the problem happens with or without it.

Let me know if I can be of any further help and thanks for the great work!

Prettier version: 1.10.2
JsPrettier version: 1.20.12
Platform: Sublime Text 3143 on Ubuntu 16.04

### Generated Prettier command line arguments
    prettier
    --stdin
    --tab-width 2
    --use-tabs false
    --stdin-filepath /path/to/MyFile.jsx
    --config /path/to/.prettierrc.json

### The contents of your `User/JsPrettier.sublime-settings` file

```
{
  "debug": true,
  "prettier_cli_path": "",
  "node_path": "",
  "auto_format_on_save": false,
  "auto_format_on_save_excludes": [],
  "allow_inline_formatting": false,
  "custom_file_extensions": [],
  "max_file_size_limit": -1,
  "additional_cli_args": {
    "--config": "/path/to/.prettierrc.json"
  },
  "prettier_options": {
    "printWidth": 100,
    "singleQuote": true,
    "trailingComma": "es5",
    "bracketSpacing": true,
    "jsxBracketSameLine": false,
    "parser": "babylon",
    "semi": true,
    "requirePragma": false,
    "proseWrap": "preserve",
    "arrowParens": "avoid"
  }
}
```

**Comment by shcallaway** [comment]
Same issue. I also noticed that `JsPrettier - Format` is no longer an option in Package Control.

**Comment by jonlabelle** [comment]
Are there any errors at all being reported in the console?

**Comment by schrockwell** [comment]
I get this error in the console when installing the package. 
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/helloworld/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 75, in <module>
    from .jsprettier.sthelper import log_debug
ImportError: cannot import name log_debug
```

**Comment by schrockwell** [comment]
Okay, now it started working again randomly and I have no idea why. 

I do have my `Packages/User` directory symlinked to Dropbox - could something have gotten out of sync there to cause the issue?

**Comment by jonlabelle** [comment]
Please try and uninstall/reinstalling the JsPrettier package. I cannot reproduce the issue, but this seems to correct the problem.
