### ISSUE TITLE
KeyError: 'bracketSpacing'

### ISSUE THREAD

**Issue by schoenwaldnils** [jonlabelle/SublimeJsPrettier#11]
When I run JsPrettier nothing happens and I get an error in the console.

I installed JsPrettier using `npm install -g prettier`

My config:
```
{
  "prettier_cli_path": "/Users/nils/.nvm/versions/node/v6.5.0/bin/prettier",
  "prettier_options": {
    "printWidth": 80,
    "singleQuote": true,
    "trailingComma": true
  }
}
```

The error I get:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/nils/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 60, in run
    prettier_options)
  File "/Users/nils/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 99, in run_prettier
    prettier_cli_opts = self.parse_prettier_option_cli_map(prettier_options)
  File "/Users/nils/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 250, in parse_prettier_option_cli_map
    option = prettier_options[mapping['option']]
KeyError: 'bracketSpacing'
```

Any idea what could cause this?

**Comment by jonlabelle** [comment]
See #5
