### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 35: invalid start byte

### ISSUE THREAD

**Issue by rgnevashev** [jonlabelle/SublimeJsPrettier#127]
$ prettier --version
    1.13.7
![2018-07-14_12-30-42](https://user-images.githubusercontent.com/123600/42723177-ebb2767c-8761-11e8-932c-cd8352d7c619.png)

**Comment by YMC-GitHub** [comment]
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "C:\Users\home\AppData\Roaming\Sublime Text 3\Packages\JsPrettier\JsPrettier.py", line 327, in run
    transformed = self.format_code(source, node_path, prettier_cli_path, prettier_options, view)
  File "C:\Users\home\AppData\Roaming\Sublime Text 3\Packages\JsPrettier\JsPrettier.py", line 371, in format_code
    error_output = stderr.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 0: invalid continuation byte

**Comment by jonlabelle** [comment]
Can't seem to reproduce on my end (tried formatting various encoded files). All I can suggest is re-installing the [package](https://packagecontrol.io/packages/JsPrettier).

**Comment by rgnevashev** [comment]
reinstall doesnt fix the issue...
