### ISSUE TITLE
Not working on vue files, no output from prettier

### ISSUE THREAD

**Issue by LogIN-** [jonlabelle/SublimeJsPrettier#129]
## Reporting an Issue

When pressing "Format Code" on VUE files nothing happens, file is not Prettier :)
When I remove "cursor-offset" from CLI prettier it works, so I guess this is more of an Prettier
issue than SublimeJsPrettier..

```

-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/usr/bin/node /usr/bin/prettier \
	--stdin \
	--no-config \
	--print-width 80 \
	--single-quote false \
	--trailing-comma none \
	--bracket-spacing true \
	--jsx-bracket-same-line false \
	--parser vue \
	--semi true \
	--require-pragma false \
	--prose-wrap preserve \
	--arrow-parens avoid \
	--tab-width 4 \
	--use-tabs false \
	--stdin-filepath /xyz/FileDetails/index.vue \
	--cursor-offset 23182

------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error(s):

[error] stdin: TypeError: options.locStart is not a function
[error]     at Object.findNodeAtOffset (/xyz/node_modules/prettier/bin-prettier.js:10017:23)
[error]     at coreFormat (/xyz/node_modules/prettier/bin-prettier.js:10203:32)
[error]     at format (/xyz/node_modules/prettier/bin-prettier.js:10369:16)
[error]     at formatWithCursor (/xyz/node_modules/prettier/bin-prettier.js:10381:12)
[error]     at Object.formatWithCursor (/xyz/node_modules/prettier/bin-prettier.js:31224:15)
[error]     at format$1 (/xyz/node_modules/prettier/bin-prettier.js:33227:21)
[error]     at /xyz/node_modules/prettier/bin-prettier.js:33321:28
[error]     at process._tickCallback (internal/process/next_tick.js:68:7)

Process finished with exit code 2


```

### Prettier version

    $ prettier --version
    1.13.7

### JsPrettier Plug-in Version
    ...
    "name": "sublime-js-prettier",
    "version": "1.20.25",
    ...

### Platform Details

Provide your Sublime Text version and Platform details.

**Example**

    - Sublime Text Version:  3.1.1
    - Sublime Text Build:3.1.7.6
    - Sublime Text Architecture: 64
    - Operating System Name: linux

### Generated Prettier command line arguments

```
/usr/bin/node /usr/bin/prettier \
	--stdin \
	--no-config \
	--print-width 80 \
	--single-quote false \
	--trailing-comma none \
	--bracket-spacing true \
	--jsx-bracket-same-line false \
	--parser vue \
	--semi true \
	--require-pragma false \
	--prose-wrap preserve \
	--arrow-parens avoid \
	--tab-width 4 \
	--use-tabs false \
	--stdin-filepath /xyz/FileDetails/index.vue \
	--cursor-offset 23182
```
        

### Is the same behavior observed when run against Prettier directly?

When the same command is passed to Prettier nothing happens there is not output nor error/exit code.
So I guess that is an issue. However when --cursor-offset  is removed I get output from prettier.
```

/usr/bin/node /usr/bin/prettier \
	--stdin \
	--no-config \
	--print-width 80 \
	--single-quote false \
	--trailing-comma none \
	--bracket-spacing true \
	--jsx-bracket-same-line false \
	--parser vue \
	--semi true \
	--require-pragma false \
	--prose-wrap preserve \
	--arrow-parens avoid \
	--tab-width 4 \
	--use-tabs false \
	--stdin-filepath /xyz/FileDetails/index.vue \
	--cursor-offset 23182

```

### The contents of your `User/JsPrettier.sublime-settings` file
```

{
	"debug": true,
}
```

https://github.com/prettier/prettier/pull/4868

**Comment by JannieT** [comment]
I don't see anything that one can set in the config to prevent the `--cursor-offset` switch from being added. Is there another workaround?
