### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by samholmes** [jonlabelle/SublimeJsPrettier#133]
Issue when running `jsPrettier: Format Code` command from command pallete.

prettier version: 1.1.0
jsPrettier Version: 1.20.26
Sublime Version: 3.1.1 Build 3176
OS: macOS 10.13.6

Error log from `` ctrl+` ``:

```
Prettier reported the following error(s):

Ignored unknown option: --no-config

Ignored unknown option: --require-pragma

Ignored unknown option: --prose-wrap

Ignored unknown option: --arrow-parens

Ignored unknown option: --stdin-filepath

Ignored unknown option: --cursor-offset
Process finished with exit code 0

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/Users/holmes/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 283, in run
    provide_cursor=True)
  File "/Users/holmes/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 406, in format_code
    return stdout.decode('utf-8'), int(new_cursor)
ValueError: invalid literal for int() with base 10: ''
```

**JsPrettier.sublime-settings**

 ```json
{
  "debug": false,
  "prettier_cli_path": "",
  "node_path": "",
  "auto_format_on_save": false,
  "auto_format_on_save_excludes": [],
  "auto_format_on_save_requires_prettier_config": false,
  "allow_inline_formatting": false,
  "custom_file_extensions": [],
  "max_file_size_limit": -1,
  "additional_cli_args": {},
  "prettier_options": {
    "printWidth": 80,
    "singleQuote": false,
    "trailingComma": "none",
    "bracketSpacing": true,
    "jsxBracketSameLine": false,
    "parser": "babylon",
    "semi": true,
    "requirePragma": false,
    "proseWrap": "preserve",
    "arrowParens": "avoid"
  }
}
```

**Comment by samholmes** [comment]
Looks like the error might be related to this commit: https://github.com/jonlabelle/SublimeJsPrettier/commit/70ce5466b2493908d752cb61fba5d4d2c21e559a

Also, the `jsPrettier: Format Code` command works when the buffer has a selection.

**Comment by kaste** [comment]
Hi @samholmes,

easiest for us would be if you update prettier. v1.1.0 is relatively old, and I think 1.4.0 is required now. 

@jonlabelle to decide if we should support older versions. 

Sorry that I introduced this bug/regression.
