### ISSUE TITLE
After upgrading Sublime, Prettier not updating file on save

### ISSUE THREAD

**Issue by jamie-kupka-acl** [jonlabelle/SublimeJsPrettier#163]
### Explain the Issue and Expected Behavior

I had my Sublime setup to run Prettier on save.  It was working fine until yesterday when I updated Sublime to 3.2 (I think I had version 3.1 up until that point) and now it does not prettify the file on save.

### Prettier version
`~/.nvm/versions/node/v7.0.0/bin/prettier --version`
1.10.2

### JsPrettier Plug-in Version
1.25.0 (got from the changelog, it is not in my package.json)

### Platform Details
Sublime Text Version: 3.2
Sublime Text Build: 3200
Operating System Name: macOS Mojave
Operating System Version: 10.14.3

### Generated Prettier command line arguments

Save a file, console outputs:
```

-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/Users/jamie_k/.nvm/versions/node/v7.0.0/bin/prettier --stdin --parser babel --use-tabs false --stdin-filepath /Users/jamie_k/src/myfile.js --loglevel debug --config-precedence prefer-file --config ./.prettierrc.yml --cursor-offset 1774

Prettier reported the following output:

[debug] normalized argv: {"_":[],"bracket-spacing":false,"color":true,"debug-check":false,"debug-print-doc":false,"editorconfig":true,"flow-parser":false,"insert-pragma":false,"jsx-bracket-same-line":false,"list-different":false,"require-pragma":false,"semi":false,"single-quote":false,"stdin":true,"support-info":false,"use-tabs":false,"version":false,"with-node-modules":false,"write":false,"parser":"babel","stdin-filepath":"/Users/jamie_k/src/myfile.js","loglevel":"debug","config-precedence":"prefer-file","config":"./.prettierrc.yml","cursor-offset":1774,"ignore-path":".prettierignore"}
[debug] load config file from './.prettierrc.yml'
[debug] loaded options `{"useTabs":false,"tabWidth":2,"printWidth":120,"trailingComma":"es5","semi":true}`

Prettier process finished with exit code 0.

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "/Users/jamie_k/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 291, in run
    provide_cursor=True)
  File "/Users/jamie_k/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 432, in format_code
    return stdout.decode('utf-8'), int(new_cursor)
ValueError: invalid literal for int() with base 10: '[debug] applied config-precedence (prefer-file): {"filepath":"/Users/jamie_k/src/myfile.js","useTabs":false,"tabWidth":2,"print'
```

My ./.prettierrc.yml:
```
useTabs: false
tabWidth: 2
printWidth: 120
trailingComma: es5
semi: true
```
My `JsPrettier.sublim-settings -- User` are blank, but in Sublime I have set up a Project where the config lives:

```
{
  "folders":
  [
    {
    "path": "."
    }
  ],
  "settings": {
    "js_prettier": {
      "debug": true,
      "prettier_cli_path": "~/.nvm/versions/node/v7.0.0/bin/prettier",
      "auto_format_on_save": true,
      "auto_format_on_save_excludes": [
      ],
      "additional_cli_args": {
        "--config": "./.prettierrc.yml",
        "--config-precedence": "prefer-file"
      }
    }
  }
}
```

Thanks.

**Comment by jamie-kupka-acl** [comment]
Oh and I did try uninstalling and reinstalling the Sublime package, and restarting computer.

**Comment by jamie-kupka-acl** [comment]
Upgraded to 1.26.0 and it works now. Thanks.
