### ISSUE TITLE
error_output = stderr.decode('utf-8')

### ISSUE THREAD

**Issue by Guxing0321** [jonlabelle/SublimeJsPrettier#196]
Hi Team,

I have faced the problem on code error

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "C:\Users\robingu\AppData\Roaming\Sublime Text 3\Packages\JsPrettier\JsPrettier.py", line 291, in run
    provide_cursor=self.disable_prettier_cursor_offset is False, is_selection=False)
  File "C:\Users\robingu\AppData\Roaming\Sublime Text 3\Packages\JsPrettier\JsPrettier.py", line 427, in format_code
    error_output = stderr.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 4: invalid continuation byte

The softversion on my laptop are bellow:
prettier  1.19.1
node:     v12.13.0
python:  3.7.4

**Comment by Guxing0321** [comment]
Hi Team，

Any update?

Please let me know if you need I provide more info on it

BR
Robin

**Comment by jonlabelle** [comment]
Sounds like the file you're trying to format has character that out-of-range in the UTF-8 spectrum.

Can you attach the file you're trying to format to this post?
