### ISSUE TITLE
JsPrettier - [Errno 13] Permission denied

### ISSUE THREAD

**Issue by archieherbias** [jonlabelle/SublimeJsPrettier#38]
I am trying to use this library in SublimeText, but I always get a Permission denied. I have change already ther permision of `/usr/bin/prettier` but still got the same permission error. The error is this:

```
/usr/lib/nodejs /usr/bin/prettier --stdin --color=false --print-width 80 --single-quote=true --trailing-comma es5 --bracket-spacing=true --jsx-bracket-same-line=false --parser babylon --semi=true --tab-width 4 --use-tabs=false
error: JsPrettier - [Errno 13] Permission denied
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "/home/user-/.config/sublime-text-3/Packages/JsPrettier/JsPrettier.py", line 192, in run
    source, node_path, prettier_cli_path, prettier_args)
  File "/home/user-/.config/sublime-text-3/Packages/JsPrettier/JsPrettier.py", line 271, in run_prettier
    shell=self.is_windows())
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
PermissionError: [Errno 13] Permission denied
```

Prettier version: 1.3.1
JsPrettier version: 1.7.8
Platform: Ubuntu 16.04
Node version: 6.10.0
Sublime version: 3
Sublime build: 3114

This is my sublime settings

```
{
	"debug": true,
	"prettier_cli_path": "/usr/bin/prettier",
	"node_path": "/usr/lib/nodejs",
	"auto_format_on_save": true,
	"allow_inline_formatting": false,
	"prettier_options": {
		"printWidth": 80,
		"singleQuote": true,
		"trailingComma": "es5",
		"bracketSpacing": true,
		"jsxBracketSameLine": false,
		"parser": "babylon",
		"useTabs": true,
		"tabWidth": 4,
	}
}
```

**Comment by archieherbias** [comment]
Nevermind, fixed this already. Just an incorrect node path.
